export const CANALES_OPCIONES = ["PRESTAMO MULTIRED", "APP MOVIL", "PAGALO", "CAJERO AUTOMATICO", "VENTANILLA"];
export const ESTADOS_ENVIO = ["NO ENVIADO", "ENVIADO"];

export const ESTADOS_DOCUMENTO = [
  "PENDIENTE",
  "NO ATENDIDO",
  "DERIVADO A RECLAMOS",
  "ATENDIDO"
];