export const CANALES_OPCIONES = ["MULTIRED VIRTUAL", "APP MOVIL", "VISA POS", "VISA COMPRAS EXTRANJERO", "VISA RETIRO ATM NO BN"];
export const ESTADOS_ENVIO = ["NO ENVIADO", "ENVIADO"];

export const ESTADOS_DOCUMENTO = [
  "PENDIENTE",
  "NO ATENDIDO",
  "DERIVADO A RECLAMOS",
  "ATENDIDO"
];